### ISSUE TITLE
[BUG] GooglePayButton ignore props.

### ISSUE THREAD

**Issue by alex-vasylchenko** [google-pay/react-native-make-payment#19]
Hi, in the example we can see that the button has several arguments, such as `radius`, `type` and `theme`. But in native code, these arguments are ignored, instead default values are used.

```
 var type = ButtonConstants.ButtonType.BUY
 var theme = ButtonConstants.ButtonTheme.DARK
 var cornerRadius = 10
```

**Comment by stephenmcd** [comment]
When I change the values for the props in the example and run it, I can see the new values reflected in the app.

Can you provide an example that reproduces the issue you're seeing?

**Comment by VadzimAlkhimionak** [comment]
I have the same problem.
The example works fine, but my current project does not change the GooglePayButton properties.
